### ISSUE TITLE
MaskedFormatter.formatString works wrong for some inputs

### ISSUE THREAD

**Issue by OlegRy** [VicMikhailau/MaskedEditText#11]
I use your library in project for phone mask. My mask is "+7 ### ### ##-##". So, there's a problem with mask. When I type number like "9998885566" and then try to get unmasked string via MaskedFormatter, all works fine and I get "9998885566". But if I type number like "9871234568" and then get unmasked string, the result is "981234568". As you can see, in unmasked string no "7" character. I think, the reason of that issue is that in mask I have "7" character and you store mask characters in list and compare each character from input with mask character without taking into account the positions.

**Comment by VicMikhailau** [comment]
Hello, OlegRy.

Thank you for your feedback!
Will be fixed as soon as possible.

**Comment by VicMikhailau** [comment]
Fixed in 2.0.2 library version.
