### ISSUE TITLE
Credit Card Mask Problem ("#### #### #### ####")

### ISSUE THREAD

**Issue by yura-f** [VicMikhailau/MaskedEditText#13]
If set mask: 
`private MaskedFormatter formatter = new MaskedFormatter("#### #### #### ####");`

Is it not work.
Why?)

**Comment by VicMikhailau** [comment]
Hello, Z-13.
Strange behavior.
Bug with replacing Editable data in MaskedWatcher. 
Please use custom MaskedEditText if it is possible.

**Comment by ghost** [comment]
I found the possible problem with the credit card.

Android: inputType can not be set to NUMBER and has a mask containing characters that are not numbers, for example "### - ###" or "###. ###"

When inputType defines as NUMBER, the mask should only have "#", if it has "-" or "." Use numberSigned or numberDecimal.

**Comment by VicMikhailau** [comment]
Hello, cafecanudo.
Thanks for your comment!
