### ISSUE TITLE
How change style&

### ISSUE THREAD

**Issue by TarasOryshhij** [VicMikhailau/MaskedEditText#2]
http://joxi.ru/Q2K7ZDPt9eJR72 - horrible design! How change on material?

**Comment by VicMikhailau** [comment]
Hello, TarasOryshhij

Please, change default EditText style: 
http://stackoverflow.com/questions/10903647/set-a-consistent-style-to-all-edittext-for-e-g
http://stackoverflow.com/questions/28081900/how-to-customize-edittext-field-in-android-using-appcompat-v721
http://www.materialdoc.com/edit-text/

Or

Create your own background for EditText:
 http://stackoverflow.com/questions/17449169/how-to-change-style-of-a-default-edittext
