### ISSUE TITLE
Set mask format programmatically

### ISSUE THREAD

**Issue by dorukkangal** [VicMikhailau/MaskedEditText#24]
Hi,

With version 3.0.2, `MaskedEditText#setMask` method marked as private.
How can i dynamically set mask format in code?

**Comment by daniellaPaiva** [comment]
Hi,

in fact, it went unnoticed. I removed the private attribute and requested the pull request. Thanks :)

**Comment by VicMikhailau** [comment]
Hi, dorukkangal .
In version 3.0.3 will be fixed.

Thanks daniellaPaiva.

**Comment by dorukkangal** [comment]
Thanks @daniellaPaiva
