### ISSUE TITLE
Fix addTextChangedListener listening 2 times

### ISSUE THREAD

**Issue by professorDeveloper** [VicMikhailau/MaskedEditText#32]
Hello, I have 2 calls to the addtextChangeListener method.
![image](https://github.com/VicMikhailau/MaskedEditText/assets/108933534/2e4deb56-a69e-4e2b-9d99-a37bfa2b27c9)
 why is that.

**Comment by VicMikhailau** [comment]
Hi,
Looks like: your input + mask setup.
Try to debug what and how changed here and in inner logic if needed.

Thanks.

**Comment by professorDeveloper** [comment]
can you help me **please** . I did not understand you. please I didn't even understand what the problem was.

**Comment by VicMikhailau** [comment]
Please check what you receive for the `s: CharSequnce?` on `onTextChanged()`. It can be **your input** + **mask applying** = **expected behavior**.

> Unfortunately, there is no way to devote much time to the project. Please feel free to Fork the project and add Pull requests. Thanks a lot!

**Comment by professorDeveloper** [comment]
I would like to send an automatic request. I am trying to prevent the api from being sent twice.

**Comment by professorDeveloper** [comment]
. Please feel free to Fork the project and add Pull requests. Thanks a lot!   I did not understand this

**Comment by VicMikhailau** [comment]
@professorDeveloper 
Please update `MaskedEditText` to `5.0.1`

`implementation("io.github.vicmikhailau:MaskedEditText:5.0.1")`

And use new methods instead 

> mMaskedEditText.addMaskedTextChangedListener
> mMaskedEditText.doBeforeMaskedTextChanged
> **mMaskedEditText.doOnMaskedTextChanged**
> mMaskedEditText.doAfterMaskedTextChanged

or

> maskedWatcher.addTextChangedListener

But it can lead to unexpected behavior in case of text changes. For your case I can suggest use pure solution like `yourEditText.text.toString()` before sent request.

Thanks.

**Comment by professorDeveloper** [comment]
thank you

**Comment by VicMikhailau** [comment]
Will be closed for now.
