### ISSUE TITLE
Deleting characters inside (###)

### ISSUE THREAD

**Issue by yura-f** [VicMikhailau/MaskedEditText#5]
Added mask: 
`pText.addTextChangedListener(new MaskedWatcher("(###)#######"));`

If after a characters input - for example: 
**(123) 4567890** reposition the cursor and erase figure **2** _(or 3 or 1)_, the input field will be: **(13**

How fix it?

Thank you!

**Comment by VicMikhailau** [comment]
Hello, Yura.

I will fix this as soon as possible.

**Comment by Mixser** [comment]
@VicMikhailau I'm fix it. Please check and merge)

**Comment by VicMikhailau** [comment]
Fixed in 2.0.0 library version.
